### ISSUE TITLE
Hemi DAI via Swap | couldn't estimate gas for swap with all tries of pool fees

### ISSUE THREAD

**Issue by surendra841** [deusexratio/Ultimate_Hemi_Testnet_Tool#2]
ERC20 token swap keeps failing, but few of the trials work in the hemi transaction explorer, but shown as fail in the script log. What is the solution to this?

And Is it possible to manually set the gas through the json file?

**Comment by fastfoodenjoyer** [comment]
Swap function returns failed mostly because it can’t count gas for the transaction 
Gas can be set manually before sending transaction, but there is very high chance that it will be failed on blockchain and you won’t get points for that, but function will return success and wallet will be marked as done, but in fact it wasn’t. In normal networks to get rid of this problem I double check every transaction if it was failed or not, that’s why you need to add etherscan api key. But in testnet Hemi scan api just doesn’t work now so I can’t do all that.

Failure to count gas specifically for token to eth swaps is mostly because permit2 signature isn’t working correctly. I added permit signature into tx data but for some reason it doesn’t work and I still haven’t figured it out. For now only solution is to do swaps via UI from every token at least once, so you will give those permits and then every other time my software will work fine
